### ISSUE TITLE
Remove manual configuration for OtlpGrpcSpanExporter

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/spring-boot-open-telemetry-demo#142]
See https://github.com/spring-projects/spring-boot/blob/3648f5f494e6b5bb010bb7f881eb748cbc0f8cc5/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/tracing/otlp/OtlpProperties.java
Replace
```
    otlp:
        metrics:
            export:
                url: http://localhost:4317
```
with `management.otlp.tracing.endpoint`
