### ISSUE TITLE
Add integration with PostgreSQL

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/spring-boot-open-telemetry-demo#95]
Create a custom schema https://www.baeldung.com/java-postgresql-create-schema-before-liquibase
and https://www.baeldung.com/jdbc-connect-to-schema

For SB3 see https://github.com/jdbc-observations/datasource-micrometer

```kotlin
dependencies {
    implementation("net.ttddyy.observation:datasource-micrometer-spring-boot")
}
```

```yaml
jdbc:
  datasource-proxy:
    include-parameter-values: true
    query:
      enable-logging: true
      log-level: INFO
  includes: QUERY
```
