### ISSUE TITLE
Add reading from Kafka

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/spring-boot-open-telemetry-demo#96]
Need also enable tracing for consumer:
```
spring:
    kafka:
        listener:
            observation-enabled: true
```
